#!/bin/bash

#./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f0o0.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f0o1.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f0o2.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f0o3.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f0o4.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f0o5.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f0o6.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f0o7.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f1o0.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f1o1.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f1o2.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f1o3.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f1o4.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f1o5.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f1o6.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f1o7.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f2o0.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f2o1.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f2o2.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f2o3.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f2o4.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f2o5.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f2o6.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f2o7.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f3o0.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f3o1.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f3o2.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f3o3.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f3o4.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f3o5.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f3o6.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f3o7.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f4o0.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f4o1.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f4o2.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f4o3.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f4o4.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f4o5.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f4o6.py
./shell.py -- script/grid_gmm.py -c config/gabordct_banca_f4o7.py
